[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Leon_Jose"]
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot>=20.0",
    "requests>=2.31.0",
    "supabase>=1.0.0"
]